### ISSUE TITLE
Create a BOM for cargo workspace

### ISSUE THREAD

**Issue by aoudiamoncef** [massalabs/massa#3656]
We could define all dependencies version in our top level workspace cargo toml file. 
workspace:
```toml
[workspace.dependencies]
tonic = { version = "0.8.3", features = ["gzip"] }
tonic-build = "0.8.4"
```
modules:
```toml
tonic = { workspace = true }
tonic-build = { workspace = true }
```

Of course you could override the version but it’s cleaner to have only one version peer workspace.

If you are interested, I’ll open an issue to keep this.

https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table
