### ISSUE TITLE
Memory consumption growing on API 

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa#4112]
## Context

In https://github.com/massalabs/massa/issues/3803 we saw that when sending operations through the API we had a memory consumption problem. More calls to `send_operations` created more memory usage.

We tested with GRPC and the problem was the same. I made a [operation injector](https://github.com/massalabs/massa/blob/b966371f7fcb02a11c0646ce2ad07e7048fe9eff/massa-node/src/operation_injector.rs#L17) to send operation directly to pool and protocol without using the API and the problems disappears.

Also when placing only a `return Ok(());` in `send_operations` we still saw a memory increase.

### Hypothesis

The module of the API or any middleware/runtime used is caching something that makes the memory growth.

## TODO

- [ ] Create a little project that use the same API setup as `massa-api` and measure the memory increase
- [ ] Find which specific config/dependency or whatever is the source of the problem
- [ ] Fix it

**Comment by aoudiamoncef** [comment]
If we have an issue with gRPC crate. This should be detected by a small set of load tests in any endpoint. 

If it's happen only for operations method this is weird. 

Stay tuned, I'll make a deep investigation and I'll be back

**Comment by aoudiamoncef** [comment]
After a making some load tests using JMeter and studying our Python script, I did a comparaison between the two with same number of workers and same number of transactions and the results...

- As we have the same issue in both JsonRPC and gRPC, the Python script seems to be more aggressive than it's equivalent in JMeter(Java) and It consumes much resources on the Massa node.

IMHO, we could have an issue with http connections 

I tuned the node maximum https connections, I set it to 1 for example, even with Python script, RAM seems stable. 

A possible fixe is to lower the parameters below to fit our needs:

```toml
[api]
    # maximum number of incoming connections allowed
    max_connections = 100
[grpc]
    # set the concurrency limit applied to on requests inbound per connection. Defaults to 32
    concurrency_limit_per_connection = 32
    # sets the SETTINGS_MAX_CONCURRENT_STREAMS spec option for HTTP2 connections
    max_concurrent_streams = 1024
```

In addition of debugging the Python script of just migrate It to Rust 🥇 to avoid surprises
